// <auto-generated />
using System;
using InvoiceGenerator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceGenerator.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210903034608_AddDefaultInvoiceOptions")]
    partial class AddDefaultInvoiceOptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence<int>("InvoiceNumbers", "shared");

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArticleNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("QuantityLowerLimit")
                        .HasColumnType("float");

                    b.Property<bool>("QuantityMonitoring")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<double>("VatRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.BankAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccontablePersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddressOfCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Company");

                    b.HasDiscriminator<string>("TypeOfCompany").HasValue("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.CompanySettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BlockClientWhenReachMaxCountOfUnpaidInvoices")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultInvoiceBankAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DefaultInvoiceLanguage")
                        .HasColumnType("int");

                    b.Property<int>("DefaultPaymentTerm")
                        .HasColumnType("int");

                    b.Property<int>("MaxCountOfUnPaidInvoices")
                        .HasColumnType("int");

                    b.Property<int>("PeriodInDaysBetweenTwoRepatedEmails")
                        .HasColumnType("int");

                    b.Property<bool>("SendAutomaticGeneratedEmails")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.HasIndex("DefaultInvoiceBankAccountId");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ContactPerson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ContactPeople");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Email", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredCompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RegisteredCompanyId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HistoryEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BulgarianMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfEvent")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfHistoryEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryEvents");

                    b.HasDiscriminator<string>("TypeOfHistoryEvent").HasValue("HistoryEvent");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BulgarainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HomePageContents");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HomePageContentToUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HomePageContentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageContentId");

                    b.HasIndex("UserId");

                    b.ToTable("HomePageContentToUser");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactPersonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfTaxEvent")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.InvoiceNumbers");

                    b.Property<bool>("IsInvoiceWithZeroVatRate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceWithoutVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonForInvoiceWithZeroVatRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("VatValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SellerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceToArticle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ArticlePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceToArticle");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceToService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PriceWithoutVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InvoiceToService");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BulgarianMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.NotificationToUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationToUser");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DefaultPriceWithoutVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("VatRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Client", b =>
                {
                    b.HasBaseType("InvoiceGenerator.Data.Models.Company");

                    b.Property<string>("MailingAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("MailingAddressId");

                    b.HasIndex("SellerId");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.RegisteredCompany", b =>
                {
                    b.HasBaseType("InvoiceGenerator.Data.Models.Company");

                    b.Property<string>("AdministratorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultInvoiceOptinsId")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AdministratorId");

                    b.HasDiscriminator().HasValue("RegisteredCompany");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ArticleHistoryEvent", b =>
                {
                    b.HasBaseType("InvoiceGenerator.Data.Models.HistoryEvent");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ArticleId");

                    b.HasDiscriminator().HasValue("ArticleHistoryEvent");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceHistoryEvent", b =>
                {
                    b.HasBaseType("InvoiceGenerator.Data.Models.HistoryEvent");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InvoiceHistoryEvent_ApplicationUserId");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("InvoiceId");

                    b.HasDiscriminator().HasValue("InvoiceHistoryEvent");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Address", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Town", "Town")
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Article", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany("Articles")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.BankAccount", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Company", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.CompanySettings", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithOne("DefaultInvoiceOptions")
                        .HasForeignKey("InvoiceGenerator.Data.Models.CompanySettings", "CompanyId");

                    b.HasOne("InvoiceGenerator.Data.Models.BankAccount", "DefaultInvoiceBankAccount")
                        .WithMany()
                        .HasForeignKey("DefaultInvoiceBankAccountId");

                    b.Navigation("Company");

                    b.Navigation("DefaultInvoiceBankAccount");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ContactPerson", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Client", "Client")
                        .WithMany("ContactList")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Email", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "RegisteredCompany")
                        .WithMany("Emails")
                        .HasForeignKey("RegisteredCompanyId");

                    b.Navigation("Client");

                    b.Navigation("RegisteredCompany");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HistoryEvent", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HomePageContentToUser", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.HomePageContent", "HomePageContent")
                        .WithMany("HomePageContentToUsers")
                        .HasForeignKey("HomePageContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", "User")
                        .WithMany("UserHomePageContent")
                        .HasForeignKey("UserId");

                    b.Navigation("HomePageContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Invoice", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.BankAccount", "BankAccount")
                        .WithMany("Invoices")
                        .HasForeignKey("BankAccountId");

                    b.HasOne("InvoiceGenerator.Data.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId");

                    b.HasOne("InvoiceGenerator.Data.Models.ContactPerson", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId");

                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Seller")
                        .WithMany("Invoices")
                        .HasForeignKey("SellerId");

                    b.Navigation("BankAccount");

                    b.Navigation("Client");

                    b.Navigation("ContactPerson");

                    b.Navigation("Seller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceToArticle", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Article", "Article")
                        .WithMany("Invoices")
                        .HasForeignKey("ArticleId");

                    b.HasOne("InvoiceGenerator.Data.Models.Invoice", "Invoice")
                        .WithMany("Articles")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Article");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceToService", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Invoice", "Invoice")
                        .WithMany("Services")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("InvoiceGenerator.Data.Models.Service", "Service")
                        .WithMany("Invoices")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Notification", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Article", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ArticleId");

                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("InvoiceGenerator.Data.Models.Invoice", null)
                        .WithMany("Notifications")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.NotificationToUser", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Notification", "Notification")
                        .WithMany("ReadFromCollection")
                        .HasForeignKey("NotificationId");

                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Service", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Town", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Country", "Country")
                        .WithMany("Towns")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Client", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.Address", "MailingAddress")
                        .WithMany()
                        .HasForeignKey("MailingAddressId");

                    b.HasOne("InvoiceGenerator.Data.Models.RegisteredCompany", "Seller")
                        .WithMany("Clients")
                        .HasForeignKey("SellerId");

                    b.Navigation("MailingAddress");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.RegisteredCompany", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ArticleHistoryEvent", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany("ArticleHistoryEvents")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("InvoiceGenerator.Data.Models.Article", "Article")
                        .WithMany("History")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.InvoiceHistoryEvent", b =>
                {
                    b.HasOne("InvoiceGenerator.Data.Models.ApplicationUser", null)
                        .WithMany("InvoiceHistoryEvents")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("InvoiceGenerator.Data.Models.Invoice", "Invoice")
                        .WithMany("History")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("ArticleHistoryEvents");

                    b.Navigation("Claims");

                    b.Navigation("Events");

                    b.Navigation("InvoiceHistoryEvents");

                    b.Navigation("Logins");

                    b.Navigation("Notifications");

                    b.Navigation("Roles");

                    b.Navigation("UserHomePageContent");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Article", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Invoices");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.BankAccount", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Country", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.HomePageContent", b =>
                {
                    b.Navigation("HomePageContentToUsers");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Invoice", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("History");

                    b.Navigation("Notifications");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Notification", b =>
                {
                    b.Navigation("ReadFromCollection");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Service", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.Client", b =>
                {
                    b.Navigation("ContactList");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceGenerator.Data.Models.RegisteredCompany", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("BankAccounts");

                    b.Navigation("Clients");

                    b.Navigation("DefaultInvoiceOptions");

                    b.Navigation("Emails");

                    b.Navigation("Invoices");

                    b.Navigation("Services");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
